---
- name: Create the jumphost
  hosts: localhost
  gather_facts: False

  vars:
      region: eu-central-1
      instance_type: t3.micro
      ami: ami-032025b3afcbb6b34  # CentOS 8.2-2.2004
      keypair: beegfs # pem file name
      pub_ip: 3.126.1.2
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-07eaa9a5491e5538d
         assign_public_ip: yes
         instance_tags:
            Name: "jump"
         exact_count: 1   
         count_tag:
           Name: jump* 
      register: newinstance     
    - name: associate an elastic IP with a device
      ec2_eip:
        in_vpc: true
        region: "{{ region }}"
        device_id: eni-03ff3158ce30658df
        public_ip: 3.126.1.2
        allow_reassociation: yes

    - name: Wait until SSH is available
      local_action:
        module: wait_for
        host: "{{ pub_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: launched_instances.instances

    - name: "Ensure Group Training exists"
      group:
        name: training
        state: present
        gid: 1001

    - name: "Add Training User"
      user:
        name: "training"
        shell: /bin/bash
        groups: training
