---
- name: Create the jumphost
  hosts: localhost
  gather_facts: False

  vars:
      region: eu-central-1
      instance_type: t3.micro
      ami: ami-032025b3afcbb6b34  # CentOS 8.2-2.2004
      dev_id: eni-0274f12b8d3f5c292
      subnet: subnet-89e391f2  
      pub_ip: 18.193.169.97
      keypair: beegfs # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
         instance_tags:
            Name: "jump"
         exact_count: 1   
         count_tag:
           Name: jump* 
      register: newinstance     
    - name: associate an elastic IP with a device
      ec2_eip:
        in_vpc: true
        region: "{{ region }}"
        device_id: "{{ dev_id }}"
        public_ip: "{{ pub_ip }}"
        allow_reassociation: yes
